name: bottom_menu_navigation
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_route: ^2.3.2
  cached_network_image: ^3.1.0

  cloud_firestore: ^2.5.2
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  #flutter_hooks: ^0.18.0 was not compatable with the version of hooks_riverpod from github. Needed to use ^0.16.0
  # flutter_hooks: ^0.16.0
  flutter_hooks: ^0.18.0
  #freezed_annotation 0.14.3 was incompatable as of 2021-08-19 with meta 1.3.0 and analyzer 1.7.1 which are required for flutter_test
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^1.0.0-dev.7
  stacked: ^2.2.5
  stacked_services: ^0.8.13
  video_player: ^2.2.0

dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.1.2
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
    #freezed 0.14.5 was incompatable as of 2021-08-19 with meta 1.3.0 and analyzer 1.7.1 which are required for flutter_test
  freezed: ^0.14.2
  #json_serializable 5.0.0 was incompatable as of 2021-08-19 with meta 1.3.0 and analyzer 1.7.1 which are required for flutter_test
  json_serializable: ^4.1.3
  #lint 1.7.2 was incompatable as of 2021-08-19 with meta 1.3.0 and analyzer 1.7.1 which are required for flutter_test
  lint: ^1.6.0
  material_design_icons_flutter: ^5.0.5955-rc.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
